### ISSUE TITLE
pyopenssl==0.13 build error on Mac

### ISSUE THREAD

**Issue by hubert3** [mwrlabs/drozer#155]
Attempting to install pyopenssl==0.13 on Mac OS X Yosemite with current Xcode, you run into the following cc error:

OpenSSL/crypto/crl.c:6:23: error: static declaration of 'X509_REVOKED_dup' follows non-static declaration

Changing the requirement to pyopenssl==0.14 fixes this.

**Comment by cacophonix** [comment]
How did you change the requirement ?

**Comment by ken5scal** [comment]
change following line, then do 'python setup.py install '

* before
```setup.py
install_requires = ["protobuf==2.4.1", "pyopenssl==0.13"],
```

* after
```setup.py
install_requires = ["protobuf==2.4.1", "pyopenssl==0.15"],
```

**Comment by HenryHoggard** [comment]
Fixed in https://github.com/mwrlabs/drozer/pull/182

**Comment by zbuc** [comment]
Issue still happens in the distributed .egg I downloaded from `https://labs.mwrinfosecurity.com/system/assets/933/original/drozer-2.3.4.tar.gz` still tries to use `pyopenssl-0.13`

**Comment by nixawk** [comment]
Is a new release package for **pyopenssl-0.1x** ? It's better to put **drozer** into https://pypi.python.org/

```
root@sh:~/andriod_security# easy_install drozer-2.3.4-py2.7.egg
Processing drozer-2.3.4-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/drozer-2.3.4-py2.7.egg
Extracting drozer-2.3.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding drozer 2.3.4 to easy-install.pth file
Installing drozer-complete script to /usr/local/bin
Installing drozer script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/drozer-2.3.4-py2.7.egg
Processing dependencies for drozer==2.3.4
Searching for pyopenssl==0.13
Reading https://pypi.python.org/simple/pyopenssl/
Downloading https://pypi.python.org/packages/8b/20/8f4230b281a2a9d0ee9e24fd89aeded0b25d40c84b3d61100a96438e1626/pyOpenSSL-0.13.tar.gz#md5=767bca18a71178ca353dff9e10941929
Best match: pyOpenSSL 0.13
Processing pyOpenSSL-0.13.tar.gz
Writing /tmp/easy_install-PvoNSh/pyOpenSSL-0.13/setup.cfg
Running pyOpenSSL-0.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PvoNSh/pyOpenSSL-0.13/egg-dist-tmp-apQ3Q5
warning: no previously-included files matching '*.pyc' found anywhere in distribution
OpenSSL/crypto/crl.c:6:23: error: static declaration of 'X509_REVOKED_dup' follows non-static declaration
 static X509_REVOKED * X509_REVOKED_dup(X509_REVOKED *orig) {
                       ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ssl.h:156:0,
                 from OpenSSL/crypto/x509.h:17,
                 from OpenSSL/crypto/crypto.h:30,
                 from OpenSSL/crypto/crl.c:3:
/usr/include/openssl/x509.h:751:15: note: previous declaration of 'X509_REVOKED_dup' was here
 X509_REVOKED *X509_REVOKED_dup(X509_REVOKED *rev);
               ^~~~~~~~~~~~~~~~
error: Setup script exited with error: command 'i686-linux-gnu-gcc' failed with exit status 1
```

```
root@sh:~/andriod_security# uname -a
Linux sh 4.6.0-kali1-686-pae #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux
```

**Comment by HenryHoggard** [comment]
You are trying to install 2.3.4 which doesn't have the fix, please install a newer version.

**Comment by nixawk** [comment]
Thanks @HenryHoggard. The newer version is ok.
